<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class permissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permisos = [
            //calendarios
            'ver-partido',
            'crear-partido',
            'editar-partido',
            'mostrar-partido',
            'desabilizar-partido',
            'eliminar-partido',
            //campeonatos
            'ver-campeonato',
            'crear-campeonato',
            'mostrar-campeonato',
            'editar-campeonato',
            'desabilizar-campeonato',
            'eliminar-campeonato',
            //cargos
            'ver-cargo',
            'crear-cargo',
            'editar-cargo',
            'desabilizar-cargo',
            'eliminar-cargo',
            //cargoOficinas
            'ver-cargoOficina',
            'crear-cargoOficina',
            'editar-cargoOficina',
            'desabilizar-cargoOficina',
            'eliminar-cargoOficina',
            //categorias
            'ver-categoria',
            'crear-categoria',
            'editar-categoria',
            'desabilizar-categoria',
            'eliminar-categoria',
            //clubs
            'ver-club',
            'crear-club',
            'editar-club',
            'mostrar-club',
            'desabilizar-club',
            'eliminar-club',
            //comisions
            'ver-comision',
            'crear-comision',
            'editar-comision',
            'desabilizar-comision',
            'eliminar-comision',
            //contribuyentes
            'ver-contribuyente',
            'crear-contribuyente',
            'editar-contribuyente',
            'desabilizar-contribuyente',
            'eliminar-contribuyente',
            //dataClubs
            'ver-dataClub',
            'crear-dataClub',
            'editar-dataClub',
            'desabilizar-dataClub',
            'eliminar-dataClub',
            //departamentos
            'ver-departamento',
            'crear-departamento',
            'editar-departamento',
            'desabilizar-departamento',
            'eliminar-departamento',
            //directClubs
            'ver-directClub',
            'crear-directClub',
            'editar-directClub',
            'desabilizar-directClub',
            'eliminar-directClub',
            //ejecutivos
            'ver-ejecutivo',
            'crear-ejecutivo',
            'editar-ejecutivo',
            'desabilizar-ejecutivo',
            'eliminar-ejecutivo',
            //empleados
            'ver-empleado',
            'crear-empleado',
            'editar-empleado',
            'mostrar-empleado',
            'desabilizar-empleado',
            'eliminar-empleado',
            //equipos
            'ver-equipo',
            'crear-equipo',
            'editar-equipo',
            'mostrar-equipo',
            'desabilizar-equipo',
            'eliminar-equipo',
            //estados
            'ver-estado',
            'crear-estado',
            'editar-estado',
            'desabilizar-estado',
            'eliminar-estado',
            //etapas
            'ver-etapa',
            'crear-etapa',
            'editar-etapa',
            'desabilizar-etapa',
            'eliminar-etapa',
            //fases
            'ver-fase',
            'crear-fase',
            'editar-fase',
            'mostrar-fase',
            'desabilizar-fase',
            'eliminar-fase',
            //genEstados
            'ver-genEstado',
            'crear-genEstado',
            'editar-genEstado',
            'desabilizar-genEstado',
            'eliminar-genEstado',
            //oficinas
            'ver-oficina',
            'crear-oficina',
            'editar-oficina',
            'desabilizar-oficina',
            'eliminar-oficina',
            //genTelefonos
            'ver-genTelefono',
            'crear-genTelefono',
            'editar-genTelefono',
            'desabilizar-genTelefono',
            'eliminar-genTelefono',
            //jugadors
            'ver-jugador',
            'crear-jugador',
            'editar-jugador',
            'mostrar-jugador',
            'desabilizar-jugador',
            'eliminar-jugador',
            //ligas
            'ver-liga',
            'crear-liga',
            'editar-liga',
            'mostrar-liga',
            'desabilizar-liga',
            'eliminar-liga',
            //periodos
            'ver-periodo',
            'crear-periodo',
            'editar-periodo',
            'desabilizar-periodo',
            'eliminar-periodo',
            //reportes
            'ver-reporte',
            'crear-reporte',
            'editar-reporte',
            'desabilizar-reporte',
            'eliminar-reporte',
            //sancions
            'ver-sancion',
            'crear-sancion',
            'editar-sancion',
            'desabilizar-sancion',
            'eliminar-sancion',
            //telefonos
            'ver-telefono',
            'crear-telefono',
            'editar-telefono',
            'desabilizar-telefono',
            'eliminar-telefono',
            //typeParameters
            'ver-typeParameter',
            'crear-typeParameter',
            'editar-typeParameter',
            'desabilizar-typeParameter',
            'eliminar-typeParameter',
            //usuarios
            'ver-usuario',
            'crear-usuario',
            'editar-usuario',
            'eliminar-usuario',
            //roles
            'ver-role',
            'crear-role',
            'editar-role',
            'eliminar-role',
        ];

        foreach ($permisos as $permiso) {
            Permission::create(['name' => $permiso]);
        }
    }
}
